// <auto-generated />
namespace EnterpriseSolution.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_BookCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_BookCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "201903211425176_update_BookCategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
